version: '3.8'
services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://cesizen-api.cyber-dodo.fr
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://cesizen.cyber-dodo.fr
    restart: unless-stopped
    networks:
      - app-network-prod

networks:
  app-network-prod:
    driver: bridge
