version: '3.8'
services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://api-prod:8080
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api-prod:8080
    restart: unless-stopped
    networks:
      - app-network-prod

networks:
  app-network-prod:
    driver: bridge