version: '3.8'
services:
  frontend-preprod:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://cesizen-api-pre.cyber-dodo.fr
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://cesizen-api-pre.cyber-dodo.fr
    restart: unless-stopped
    networks:
      - app-network-preprod

networks:
  app-network-preprod:
    driver: bridge