name: PR CI (web - build)

on:
  pull_request:
    branches: [ master, preprod, dev ]

permissions:
  contents: read

concurrency:
  group: pr-ci-web-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (PR - Next.js)
    runs-on: ubuntu-latest
    env:
      CI: "true"
      NEXT_TELEMETRY_DISABLED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node 20 + cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # Installe pnpm (officiel)
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # Fallback si jamais pnpm n’est pas sur le PATH (rare mais utile pour diagnostiquer)
      - name: Ensure pnpm is available
        run: |
          if ! command -v pnpm >/dev/null 2>&1; then
            echo "pnpm not found, installing globally..."
            npm i -g pnpm@9
          fi
          pnpm -v

      # (optionnel) Cache du cache Next pour accélérer les builds
      - name: Cache .next/cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: next-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('next.config.*', 'tsconfig.json') }}
          restore-keys: |
            next-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}-

      - name: Install deps
        run: pnpm install --frozen-lockfile

      # - name: Lint
      #   run: pnpm run lint --if-present

      # - name: Type check
      #   run: pnpm run typecheck --if-present

      - name: Build Next.js
        run: pnpm run build
