name: PR CI (web - Next.js)

on:
  pull_request:
    branches: [ master, preprod, dev ]

permissions:
  contents: read

concurrency:
  group: pr-ci-web-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (PR - Next.js)
    runs-on: ubuntu-latest
    env:
      CI: "true"
      NEXT_TELEMETRY_DISABLED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (20) + pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable Corepack (pnpm)
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build Next.js
        run: pnpm run build